### ISSUE TITLE
The plugin not working with ionic project

### ISSUE THREAD

**Issue by bluety** [avivais/phonegap-parse-plugin#42]
How to install this plugin with ionic project ?

**Comment by fabriciojs** [comment]
I am installing it using the cordova CLI.

However, the plugin never gets available on the app's javascript scope (**ReferenceError: parsePlugin is not defined**)

Any clues on what to do from here?

**Comment by bluety** [comment]
No idea, you test on a phone ?

**Comment by fabriciojs** [comment]
Yes, on a phone. A try/catch tells me the error.

I got it to work! It was my bad (and a bit of Ionic's bad too).

Actually, just realised, on the battle to make it work I have installed what can be other version of this plugin - via plugin registry (http://plugins.cordova.io/#/package/com.parse.cordova.core.pushplugin).

`ionic plugin add com.parse.cordova.core.pushplugin`

Then, when I tried to access `parsePlugin` on the Javascript, the variable did not exist - JUST YET.

I was trying to do so on a ng service called from my main ng controller.

I remembered of the raw cordova way, and the deviceready event - which I assumed Ionic was already taking into account to start my app/controllers/services. Turns out Ionic does not consider it.

So I just wrapped my code (the piece that deals with `parsePlugin`) with the event like this:

```
document.addEventListener("deviceready", function() {
    try {
      parsePlugin.initialize(...);
      alert("it works!");
    } catch (ex) {
      alert("ERROR: "+ex);
    }
  }, false);
```

Ta-da! It works now.

Hope this can help.

**Comment by bluety** [comment]
Did you manage to save the phone in Installation class ?

**Comment by jak1192** [comment]
@bluety Any luck? Same issue..

**Comment by quanghoc** [comment]
Which Ionic and Cordova version do you use?

I have the latest and it gave error when build:

```
** BUILD FAILED **


The following build commands failed:
    CompileC build/ParsePush.build/Debug-iphonesimulator/ParsePush.build/Objects-normal/i386/CDVParsePlugin.o ParsePush/Plugins/com.parse.cordova.core.pushplugin/CDVParsePlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/hawk/Documents/ParsePush/platforms/ios/cordova/build-debug.xcconfig,-project,ParsePush.xcodeproj,ARCHS=i386,-target,ParsePush,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/hawk/Documents/ParsePush/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/hawk/Documents/ParsePush/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/hawk/Documents/ParsePush/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/hawk/Documents/ParsePush/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```
